Feature/pace l1b converter
JCSDA-internal/ioda-converters pull request #1062
Opened 2022-09-23 00:10 UTC by HamidehGMAO

## Description

We add a converter to convert simulated radiance data for PACE mission. This is to convert PACE L1B data. We already implemented a converter for the PACE L2 data. Data can be obtained from https://oceandata.sci.gsfc.nasa.gov/directdataaccess/Level-1B/PACE_OCI/2019/

### Issue(s) addressed

Link the issues to be closed with this PR

https://github.com/JCSDA-internal/ioda-converters/issues/1061
- fixes #1061

2022-09-23 11:24 UTC, liuxiao37k commented
@HamidehGMAO Thanks for sharing the converter! Looks like `ci` still has some complaints. I'll test later, but today for sure!

2022-09-23 19:02 UTC, mjhossen approved these changes

2022-09-23 19:24 UTC, liuxiao37k commented
@HamidehGMAO I tested the batch download shell script with soca-science and it worked perfectly (after replacing USERNAME/PASSWORD part with `--load-cookies ~/.netrc` in the `wget` command). I unfortunately won't be able to test the converter leaving for vacation shortly. Sorry!

A quick question: does the converter loop through all the Level 1b swaths downloaded to the same folder (by soca-science, to `./SCRATCH/2019032112/prep.obs/dwnld/radiance`) and concatenate them to a single converted file like [this Level2 converter](https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/marine/viirs_modis_l2_oc2ioda.py) does? Thank you! I should have looked into the code myself but I am running out of time today...

@mjhossen were you able to test the download script and converter in soca-science by running `prep` step for `EXP_START_DATE=20190321Z12`?

2022-09-23 20:14 UTC, HamidehGMAO commented
@liuxiao37k Thanks for looking at the download script. There is a test in this PR ([test/CMakeLists.txt](https://github.com/JCSDA-internal/ioda-converters/pull/1062/files#diff-33394812ba204689144fd2f80832db83853ba1cb32403edb4e15fe4893e675fd)) which test the converter for a sample data "testinput/pace_radiance_L1B.nc" but you can test it for more data.

2022-09-27 20:06 UTC, BenjaminRuston commented
@HamidehGMAO are there new data files associated with this PR?

2022-09-27 20:31 UTC, HamidehGMAO commented
> @HamidehGMAO are there new data files associated with this PR?

@BenjaminRuston There are just 5 days of simulated data from [21 Mar 2019](https://oceandata.sci.gsfc.nasa.gov/directdataaccess/Level-1B/PACE_OCI/2019/080/) to 25 Mar 2019 available for PACE mission. In this PR we just used a small sample data for 20190321.

2022-09-28 14:32 UTC, travissluka requested changes

2022-09-28 14:32 UTC, travissluka commented on src/marine/pace_radiance2ioda.py
> +        type=int, default=1)
seems threads aren't used, so remove this

2022-09-28 14:54 UTC, HamidehGMAO commented on src/marine/pace_radiance2ioda.py
> +        help="path of patmosx avhrr observation input file(s)",
oops! Just fixed it

2022-09-28 16:17 UTC, HamidehGMAO commented on src/marine/pace_radiance2ioda.py
> +    VarAttrs[('radiance', 'ObsValue')]['_FillValue'] = 999
just fixed it. Could you please review it now. Thanks

2022-09-28 16:53 UTC, kbhargava approved these changes

2022-09-28 20:36 UTC, travissluka approved these changes

2022-09-28 20:37 UTC, merged