Update the sprint branch again with develop changes mostly for BUFR (via PR1100)
JCSDA-internal/ioda-converters pull request #1138
Opened 2023-01-03 22:41 UTC by gthompsnJCSDA

## Description

This PR again updates the top-level sprint branch to incorporate changes from develop (I think almost entirely PR1100).  With this update, we should be back on track to fixing the broken ctests related to naming convention changes so we can move ahead with the big push to get all sprint branches (UFO and IODA and all associates) to merge into develop in the next 2 weeks.

### Issue(s) addressed

A separate one was not created.

## Acceptance Criteria (Definition of Done)

Fixing as many ctests as possible.

## Dependencies

Not waiting on other PRs (yet)

## Impact

Keeping in sprint branch until ready for merge to develop.

2023-01-04 16:57 UTC, gthompsnJCSDA commented
Making this PR a draft until fixing a bunch of the 92 failed ctests.  Do not review yet.

2023-01-04 23:04 UTC, BenjaminRuston commented on src/gsi-ncdiag/gsi_ncdiag.py
> +    'releaseTime': ('releaseTime', 'integer'),
believe the left hand side is the `GSI` variable name so should remain as `LaunchTime` but am not entirely sure

2023-01-10 18:34 UTC, BenjaminRuston approved these changes
this looks like it is needed!   should get this in ASAP I would assume

2023-01-10 18:34 UTC, BenjaminRuston commented
@gthompsnJCSDA this is quite large, is there anyway to break it up and get a part of it in now

2023-01-10 20:24 UTC, srherbener approved these changes
Great progress - down to 15 test failures on all three compilers. The rest of the tests can be addressed in subsequent PRs. Thanks for all your hard work to get this accompilished!

2023-01-10 20:29 UTC, srherbener commented
@BenjaminRuston did you mean to reset your review?

Given that we will accept with test failures for this PR, is this ready to merge now? The companion PR in ioda is ready. thanks!

2023-01-10 20:54 UTC, jeromebarre requested changes
I think that the changes proposed in the tropomi conveter will produce files that won't work in UFO and this cannot be done at the moment due to constrains in IODA.

2023-01-10 21:59 UTC, srherbener commented
> I think that the changes proposed in the tropomi conveter will produce files that won't work in UFO and this cannot be done at the moment due to constrains in IODA. Same goes with MOPITT CO but changes haven't been made or at least I haven't seen it.

@jeromebarre is this referring to the averaging kernel variables that cannot be 2D yet. That is, they need to remain as a set of 1D variables with the level (?) number attached as a suffix. If so, which specific sets of variables need to remain 1D? Thanks!

2023-01-11 00:32 UTC, srherbener commented
@jeromebarre I've been informed from the OBS team that the agreed upon plan is to merge this PR as is, and revert the tropomi converter to the current develop version if necessary (before the Fortran API shows up).

Is that your understanding? Are you okay with merging as is?

2023-01-11 07:44 UTC, jeromebarre commented
Yes this refers to the averaging kernel and pressure vertices arrays and other ancillary variables such as the apriori quantities. Merging the tropomi converter as is as this will produce useless IODA files, i.e. breaking the converter. We will most likely have to revert most of the changes made but at this point it now feels that we ought to merge as is otherwise we'll waste even more time and energy on this. Thanks for checking anyway.

2023-01-11 15:19 UTC, srherbener commented
@jeromebarre thank you for you generous patience and understanding.

2023-01-11 15:19 UTC, srherbener commented
We still need another reviewer approval before merging.

2023-01-11 15:20 UTC, merged