Longitude/latitude displacement addition to the high-resolution radiosonde YAML
JCSDA-internal/ioda-converters pull request #1202
Opened 2023-04-05 19:35 UTC by PraveenKumar-NOAA

## Description

This PR adds the longitude/latitude displacement to the existing high-resolution radiosonde YAML, which is required by both global and regional users, and also replaces dewpointTemperature with dewPointTemperature.

### Issue(s) addressed

This PR partially addresses the following issue #1184. 

## Acceptance Criteria (Definition of Done)

Good reviews and pass the ctest.

## Dependencies

None

## Impact

None

2023-04-05 20:16 UTC, MatthewMorris-NOAA approved these changes
Looks good.

2023-04-06 17:59 UTC, BenjaminRuston commented on test/testinput/bufr_ncep_highRes_sonde.yaml
> +            query: "*/UARLVB/LATDH"
what are they using for GNSS-RO, this too has a single value and then individual ones for each level.  the code is designed for a displacement from a single value (as this is pretty specific to a data type)? Or should the converter compute the lat/lon at each vertical point and store this instead.

@emilyhcliu do you have any input on this?

2023-04-10 18:07 UTC, BenjaminRuston requested changes
can we add level by level latitude and longitude like we do for other observation types such as `gnss_ro` rather than add a new convention for `levelLatitudeDisplacement`

@emilyhcliu ?

2023-04-11 15:12 UTC, PraveenKumar-NOAA commented
> can we add level by level latitude and longitude like we do for other observation types such as `gnss_ro` rather than add a new convention for `levelLatitudeDisplacement`
> 
> @emilyhcliu ?

@BenjaminRuston this is required by the regional RTMA/URMA users and @MatthewMorris-NOAA is the right person to answer this. I am not adding a new convention here, this already exists into the conventional table.

2023-04-11 16:26 UTC, emilyhcliu commented
> can we add level by level latitude and longitude like we do for other observation types such as `gnss_ro` rather than add a new convention for `levelLatitudeDisplacement`
> 
> @emilyhcliu ?

@BenjaminRuston, what is the official name of the gnss_ro (level by level lat/lon) data you mention in the IODA naming convention?  If the proper variable name for radiosonde data displacement already exists, we have no objection to adopting the name you suggest.

2023-04-11 19:12 UTC, PraveenKumar-NOAA commented
@BenjaminRuston @MatthewMorris-NOAA @emilyhcliu @PatNichols please check the [WMO Table](https://confluence-test.ecmwf.int/display/ECC/WMO%3D35+element+table#WMO=35elementtable-CL_5), the displacement data is defined as: 

005015 --- latitudeDisplacement
006015 --- longitudeDisplacement

I am using the variables already in the [ObsSpace.yaml](https://github.com/JCSDA-internal/ioda/blob/develop/share/ioda/yaml/validation/ObsSpace.yaml#L1227). 

I also extracted values of these variables directly from the BUFR file, I hope this will help: 

005015  LATDH                    0.58870  DEGREE                        LATITUDE DISPLACEMENT (HIGH ACCURACY)
005015  LATDH                    0.58988  DEGREE                        LATITUDE DISPLACEMENT (HIGH ACCURACY)
005015  LATDH                    0.59110  DEGREE                        LATITUDE DISPLACEMENT (HIGH ACCURACY)

006015  LONDH                    1.66105  DEGREE                        LONGITUDE DISPLACEMENT (HIGH ACCURACY)
006015  LONDH                    1.66371  DEGREE                        LONGITUDE DISPLACEMENT (HIGH ACCURACY)
006015  LONDH                    1.66650  DEGREE                        LONGITUDE DISPLACEMENT (HIGH ACCURACY).

2023-04-11 21:39 UTC, emilyhcliu commented
@MatthewMorris-NOAA Thanks for the confirmation.  We will ensure the global file contains the actual (true) location (lat/lon) of the observations.

2023-04-11 21:42 UTC, emilyhcliu commented
@BenjaminRuston We will drop the displacement data from the IODA file.  And, we will add the processing to create the actual lat/lon from the lunch point lat/lon plus the displacement in the bufr converter.

2023-04-13 17:44 UTC, emilyhcliu approved these changes

2023-04-13 17:52 UTC, MatthewMorris-NOAA approved these changes

2023-04-17 17:58 UTC, BenjaminRuston approved these changes
excellent thanks!

2023-04-18 14:40 UTC, merged