Fix retrieval surface and obs error in viirs_aod2ioda.py
JCSDA-internal/ioda-converters pull request #1205
Opened 2023-04-10 16:14 UTC by ypwang19

## Description

This PR fixed the VIIRS AOD obs error estimation based on retrieval surface (QCPath) in viirs_aod2ioda.py

The QCPath are 8-bit integers and should be interpreted bit by bit. Briefly, if the right most bit equals 1, the data is retrieved from water; if the second right most position equals 1, the data is retrieved from bright land; otherwise (both equal 0), it is from dark land.

### Issue(s) addressed

Link the issues to be closed with this PR
- Correct obs error estimation based on surface type in viirs_aod2ioda.py ##<[1201](https://github.com/JCSDA-internal/ioda-converters/issues/1201)>

## Acceptance Criteria (Definition of Done)

Good reviews.

## Dependencies
None.

## Impact
None.

2023-04-10 17:47 UTC, jeromebarre requested changes
Thanks for making those changes but please update the reference for the test associated with ioda viirs.

2023-04-10 18:50 UTC, CoryMartin-NOAA approved these changes
Approved pending updating of test reference file as Jerome mentioned and we just discussed in our EMC meeting.

2023-04-11 01:30 UTC, andytangborn approved these changes
I agree with Cory and approve pending the reference file getting merged.

2023-04-11 15:32 UTC, jeromebarre approved these changes

2023-04-11 17:49 UTC, merged