fix channel number for amsr2
JCSDA-internal/ioda-converters pull request #1333
Opened 2023-08-18 13:17 UTC by BenjaminRuston

## Description

the channel number should begin with 1

## Issue(s) addressed

Resolves #1332

2023-08-18 13:18 UTC, BenjaminRuston commented
@smaticka this is the small issue I noted leaving this as a draft until we complete the testing through the minimization

2023-08-18 22:56 UTC, smaticka approved these changes
I was able to run both `hofx3d-c384` and `skylab-atm-land` (with `monitoring` on) with the converted data. 

Thanks @BenjaminRuston !

2023-08-21 18:03 UTC, PatNichols approved these changes
Look good

2023-08-22 01:13 UTC, PatNichols commented
@BenjaminRuston Looks like this is good to go except for coding norms failures.

2023-08-22 17:12 UTC, BenjaminRuston commented
@smaticka, @PatNichols and @fcvdb have verified the longitudes in the raw files are -180 - 180 following convention

2023-08-23 01:19 UTC, fabiolrdiniz requested changes
Thanks, @BenjaminRuston! The same needs to be done for `solarAzimuthAngle` & `solarZenithAngle` (commented out).

2023-08-23 01:19 UTC, fabiolrdiniz commented on src/hdf5/amsr2_2ioda.py
>      obs_data[(k, metaDataName)] = np.array(f['Earth Azimuth'], dtype='float32').flatten()
```suggestion
    obs_data[(k, metaDataName)] = np.array(f['Earth Azimuth']*f['Earth Azimuth'].attrs['SCALE FACTOR'][0], dtype='float32').flatten()
```

2023-08-23 02:30 UTC, fabiolrdiniz approved these changes
Thanks, @BenjaminRuston!

2023-08-24 18:04 UTC, merged