Update AirNow converter
JCSDA-internal/ioda-converters pull request #1541
Opened 2024-08-13 17:46 UTC by weiwilliam

## Description
This PR updates the converter for AirNow observations with, 
1. Add land use to variable `surfaceQualifier` (0=UNKNOWN, 1=RURAL, 2=SUBURBAN, 3=URBAN AND CENTER CITY) based on a full site list provided by EPA
2. multifiles capability 

## Issue(s) addressed

Resolves #1297 

## Dependencies

List the other PRs that this PR is dependent on:
- [ ] ...

## Impact

Expected impact on downstream repositories:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have run the unit tests before creating the PR

2024-08-13 17:46 UTC, weiwilliam commented
@jeromebarre and @mer-a-o Is `surfaceQualifier` good to store land use information?

2024-08-27 19:27 UTC, mer-a-o requested changes
The test is failing for me:
```
66: Traceback (most recent call last):
66:   File "/discover/nobackup/mabdiosk/jedi-bundle/build-gnu-spack-1.7.0-mil/bin/airnow2ioda_nc.py", line 203, in <module>
66:     time_offset = round((dt - epoch).total_seconds())
66: TypeError: can't subtract offset-naive and offset-aware datetimes
```
Can you add an option to take the assimilation window from the user and convert only within that window? Similar to what @jeromebarre added here: https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/mopitt_co_nc2ioda.py#L152

2024-08-27 19:27 UTC, mer-a-o commented on src/compo/airnow2ioda_nc.py
> +#iso8601_string = locationKeyList[meta_keys.index('dateTime')][2]
remove these lines if they are not needed.

2024-08-27 19:27 UTC, mer-a-o commented on src/compo/airnow2ioda_nc.py
> +        help="define this if sitefile is a full list",
What does full list mean? Can you make it a little more clear?

2024-08-27 23:13 UTC, weiwilliam commented on src/compo/airnow2ioda_nc.py
> +        help="define this if sitefile is a full list",
I will update it to `--epa_list` and modify the description to "define this if the sitefile contains land use information from EPA".

2024-08-27 23:14 UTC, mer-a-o commented
@weiwilliam I rebuilt the code and the error went away. But I'm getting a different error:
```
66: Processing infile= testinput/airnow_2020081306.dat
66: DIFFER : NUMBER OF GLOBAL ATTRIBUTES : 7 <> 6
66: DIFFER : VALUES OF GLOBAL ATTRIBUTE : source : "https://files.airnowtech.org/?prefix=airnow/" <> "Unknown (ftp)"
66: DIFFER : NAME OF GLOBAL ATTRIBUTE : sourceFiles : GLOBAL ATTRIBUTE DOESN'T EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : carbonmonoxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : nitrogendioxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : sulfurdioxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : carbonmonoxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : nitrogendioxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : sulfurdioxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : carbonmonoxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : nitrogendioxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
66: DIFFER : VARIABLE : sulfurdioxideSurface : DOES NOT EXIST IN "testoutput/airnow_2020081306.nc"
1/1 Test #66: test_iodaconv_airnow .............***Failed    1.51 sec
```

2024-08-27 23:19 UTC, weiwilliam commented
@mer-a-o Yes, the testoutput is not updated, because I would like to know whether `surfaceQualifier` is good to use. The current usages are 0=land, 1=sea, and 2=seaice.

2024-08-28 01:07 UTC, mer-a-o commented
How about `stationType`:  https://github.com/JCSDA-internal/ioda/blob/develop/share/ioda/yaml/validation/ObsSpace.yaml#L1075?

2024-08-28 21:20 UTC, weiwilliam commented
I also considered that, but the description said "type of station such as ASOS, AWOS".
Then it would be "AirNow" in this case.
I use "surfaceQualifier" because there is another variable "earthSurfaceType" noted with "better for future".

@BenjaminRuston Can you suggest a variable that fits "land use" information better, such as "rural" and "urban"? Thanks.

2024-08-29 19:46 UTC, jeromebarre commented
replace `surfaceQualifier` by `airqualityClassification`
i.e. https://www.eea.europa.eu/en/topics/in-depth/air-pollution/monitoring-station-classifications-and-criteria

2024-08-29 19:53 UTC, jeromebarre requested changes
Looks good to me I haven't had time to test yet. Please address the comment of the classification variable above.

2024-08-29 20:00 UTC, weiwilliam commented
@jeromebarre Thank you! I will update it and address Maryam's comments.

2024-08-30 21:36 UTC, weiwilliam commented
We will need to add the following variables into ObsSpace.yaml for validation:
```
MetaData/airqualityClassification
[ObsValue, ObsError, PreQC]/particulatematter2p5Surface
[ObsValue, ObsError, PreQC]/ozoneSurface
[ObsValue, ObsError, PreQC]/carbonmonoxideSurface
[ObsValue, ObsError, PreQC]/nitrogendioxideSurface
[ObsValue, ObsError, PreQC]/sulfurdioxideSurface
```

2024-09-13 14:20 UTC, mer-a-o commented on test/CMakeLists.txt
>                            -o testrun/airnow_2020081306.nc"
@weiwilliam you are missing the last line of `ecbuild_add_test` command here.

2024-09-13 14:21 UTC, mer-a-o commented on test/CMakeLists.txt
>                            -o testrun/airnow_2020081306.nc"
Are you going to update `testoutput/airnow_2020081306.nc` ?

2024-09-13 15:07 UTC, weiwilliam commented on test/CMakeLists.txt
>                            -o testrun/airnow_2020081306.nc"
No, there is another new test `test_${PROJECT_NAME}_airnow_epalist` below, which use the same input but different output.

2024-09-13 15:13 UTC, weiwilliam commented on test/CMakeLists.txt
>                            -o testrun/airnow_2020081306.nc"
@mer-a-o thank you, I see the missing line.

2024-09-13 17:02 UTC, mer-a-o commented
@weiwilliam Do the airnow tests pass for you? Do you need to update the reference files?

2024-09-13 17:57 UTC, weiwilliam commented
@mer-a-o I put the csv file in the wrong place, and I will update the variables in original testoutput.

2024-09-13 19:13 UTC, mer-a-o approved these changes

2024-09-16 15:55 UTC, mer-a-o commented
@weiwilliam I'm looking at `testrun/airnow_2020081306.nc` why all the values are 0.1 for all the measured species?

2024-09-16 20:04 UTC, weiwilliam commented
@mer-a-o let me check.

2024-09-16 20:24 UTC, weiwilliam commented
@mer-a-o were you checking ObsError? ObsError is filled with 0.1 at all data points.

2024-09-16 20:28 UTC, mer-a-o commented
@weiwilliam Yes!! Sorry for the false alarm.

2024-09-17 14:19 UTC, jeromebarre commented
> @mer-a-o were you checking ObsError? ObsError is filled with 0.1 at all data points.

This is because Airnow doesn't provide the obs error. In the future, if we want to assimilate air now it would be good to do a little bit of research to see if in the literature there is a way to estimate the error for DA and implement it in the converter. If this doesn't exist this is a little project that we should carry forward. This is important for regional AQ DA.

2024-09-17 14:22 UTC, jeromebarre approved these changes

2024-09-19 16:47 UTC, BenjaminRuston commented on src/compo/airnow2ioda_nc.py
> +import os, sys
```suggestion
import os
```

i do not see this being used

2024-09-19 16:50 UTC, BenjaminRuston commented
not particularly satisfied with the state of `surfaceQualifier` as in the ioda validation yaml, and this PR is perfectly valid but the values are ambiguous as to what they refer to:

https://github.com/JCSDA-internal/ioda/blob/d49ed17e115f5d7ff3310cd1dfe4798c10aa03db/share/ioda/yaml/validation/ObsSpace.yaml#L1274C1-L1274C80

```
  - Variable: [ "surfaceQualifier", "surface_type" ]  # 0=land, 1=sea, 2=seaice
  ```

2024-09-19 16:53 UTC, weiwilliam commented
@BenjaminRuston Sorry, I forgot to update the PR description at the top. We are using `airqualityClassification` now.

2024-09-19 19:53 UTC, BenjaminRuston commented
> @BenjaminRuston Sorry, I forgot to update the PR description at the top. We are using `airqualityClassification` now.

yes seeing that... the `airqualityClassification` is not in the IODA standards we need to add this and am changing it to `airQualityClassification`

will update this PR, please note this change and lets use this moving forward

2024-09-19 20:02 UTC, BenjaminRuston commented
@weiwilliam updated the name please review and let me know if this work

we will need to update:
share/ioda/yaml/validation/ObsSpace.yaml

please go ahead and put a PR into IODA to add this new Qualifier and we should have folks review across agencies

2024-09-19 20:04 UTC, BenjaminRuston approved these changes
@weiwilliam this seems fine, there are two `airnow_sites` files now... one which has the `epalist` and requires the argument it appears.  We could potentially also make this option irrelevant if the `airnow_sites` file is the driver behind this true or false of the epalist

2024-09-19 22:40 UTC, BenjaminRuston commented
@weiwilliam we should talk there's likely a JEDI integration test expecting the kinda camel case name `airqualityClassification` ... but this is another thing would like to fix as:

![image](https://github.com/user-attachments/assets/f9ebfe4b-dfbf-489f-84c0-1eb170fd07e2)


and though I completely understand that this is an "air-quality" Classification.... camelCase is agnostic to the words and would like to just follow and not redefine *camel case* with new entries

2024-09-20 15:07 UTC, merged