Assigning error to DerivedObsValues. OSW
JCSDA-internal/ioda-converters pull request #1545
Opened 2024-08-22 15:08 UTC by smaticka

## Description

Ocean surface winds, osw, are data only containing wind spd. the components are calculated using an ObsFunction, which store the components in DerivedObsValues group. We aren't able to assign ObsError to the DerivedObsValue group. This PR creates a workaround for that. 

ObsValue/windEastward and ObsValue/windNorthward are initiated in the converter as 0's, which makes them `observed variables` in addition to the `simulated variables` and allows for error assignment. Missing values are also assigned in colocations as missing wind speed values. 

skylab yamls need to be updated to match what worked in the ctest. 

to test it, I ran the `fv3-jedi` ctest: `fv3jedi_test_tier1_hyb-3dvar` with an obsSpace for CYGNSS and the needed variables. It is able to process the CYGNSS obs and creates an hofx of the wind components and has the expected ObsErrors we assign. 

## Dependencies

skylab PR: 

## Checklist

- [x] a converted obs file of CYGNSS runs with hofx 
- [x] the correct ObsError is assigned
- [ ] the skylab yamls are updated

2024-08-22 15:32 UTC, fabiolrdiniz requested changes
Thanks, @smaticka! Please, notice this file uses 4-space indentation, so I suggest you to adjust your changes to that too.

2024-08-27 12:05 UTC, smaticka commented
@fabiolrdiniz, thanks. the coding changes have been made and it should be good to go after the skylab PR is submitted. I believe the only test that is failing is not related to this PR.. 
<img width="743" alt="image" src="https://github.com/user-attachments/assets/441a3871-91b7-4b43-8f59-aaaee770982e">

2024-08-27 12:07 UTC, smaticka commented
also, noting that the current handling of PreQC is to reject all windSpeed values that have 'bad' flags. The desired functionality is to assign the flags and let the user choose the flags to use. Currently we are not able to pass on the PreQC flags to the wind components, so this needs to be addressed (perhaps another PR).

2024-08-27 16:18 UTC, fabiolrdiniz approved these changes

2024-08-27 16:20 UTC, fabiolrdiniz commented on src/hdf5/osw_2ioda.py
> +    obsvars_ttl = obsvars_0s
It is not clear to me why you need this variable.

2024-08-27 16:21 UTC, fabiolrdiniz commented on src/hdf5/osw_2ioda.py
> +    obs_data[obsvars_0s[1]+obsQcName] = 0.
QC flags are integers.

2024-08-27 17:39 UTC, smaticka commented
should be good now

2024-09-04 22:02 UTC, BenjaminRuston commented on src/hdf5/osw_2ioda.py
> +    for iodavar in obsvars_0s:
this is incorrect and will not set the variable attributes for the 'Windspeed' variable

2024-09-04 22:02 UTC, BenjaminRuston commented on src/hdf5/osw_2ioda.py
> +        if iodavar == 'windSpeed':
`iodavar` will never be 'windSpeed'

2024-09-04 22:05 UTC, BenjaminRuston commented on src/hdf5/osw_2ioda.py
> +    obsvars_0s.insert(0, obsvars[0])
ahhh I see this works but is confusing

2024-09-24 16:46 UTC, BenjaminRuston commented on src/hdf5/osw_2ioda.py
> +    obsvars_dummy.insert(0, obsvars[0])
this really should be changed as it's adding the *true* observable to the `dummy` array which is just confusing for human readibility

2024-09-25 20:33 UTC, BenjaminRuston approved these changes
thanks @smaticka a couple more small changes this now completed

2024-09-26 14:49 UTC, merged

2024-09-26 14:49 UTC, fcvdb approved these changes
Thanks!