Feature/smos l2nrt ssm
JCSDA-internal/ioda-converters pull request #410
Opened 2021-01-27 13:26 UTC by YoulongXia-NOAA

## Description

Initial Implementation for SMOS Level 2 NRT Soil Moisture

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #408 

## Dependencies

No dependencies

## Impact

No

2021-01-27 13:30 UTC, aerorahul requested changes

2021-01-27 13:30 UTC, aerorahul commented on test/CMakeLists.txt
> +                            "${CMAKE_BINARY_DIR}/bin/smos_ssm2ioda.py
This needs to be PROJECT_BINARY_DIR

2021-01-27 13:31 UTC, YoulongXia-NOAA commented
Dear my colleagues,

I have developed a converter for SMOS Level 2 NRT soil moisture in support JEDI land DA activity. When your time is available, please review it. Thank you.

2021-01-27 13:41 UTC, aerorahul approved these changes

2021-01-27 21:29 UTC, CoryMartin-NOAA approved these changes

2021-01-28 20:21 UTC, srherbener approved these changes
Looks good. Thanks for contributing this script.

2021-01-28 20:21 UTC, merged

2021-01-28 21:28 UTC, YoulongXia-NOAA commented
Thank you all for your review. This work is done now.  Have a good day and weekend.