Feature/query atovs
JCSDA-internal/ioda-converters pull request #713
Opened 2021-11-30 09:04 UTC by emilyhcliu

## Description

This PR includes the following:
(1) add the BUFR conversion to IODA for IASI, RARS/DB AMSU-A, and RARS/DB MHS in the NCAR BUFR2NC Fortran utility
(2) add two NCEP BUFR tables for satellite radiance data: normal-feed and RARS/DB
(3) add BUFR2IODA YAML files for normal-feed RARS/DB AMSU-A and MHS BUFR data
(4) add tests and associated input/output test data files

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #422
- fixes #423

2021-11-30 09:50 UTC, emilyhcliu commented on test/CMakeLists.txt
> +                    DEPENDS bufr2ioda.x )
@rmclaren There are two tests related to BUFR2IODA conversion in this PR:
test_iodaconv_bufr_1bamua2ioda and test_iodaconv_bufr_esamua2ioda

The test_iodaconv_bufr_1bamua2ioda takes 12 seconds to complete.  However, the test_iodaconv_bufr_esamua2ioda takes about 110 seconds to finish.

The size of the input BUFR file for these two tests are the following:
gdas.t12z.1bamua.tm00.bufr_d  --- 3241840 kb
gdas.t12z.esamua.tm00_bufr_d --- 2619528 kb

The run time for esamua is much longer despite the size of the input files are similar.  

The offline tests using the following:
/build/bin/bufr2ioda.x  bufr_ncep_1bamua.yaml
/build/bin/bufr2ioda.x  bufr_ncep_esamua.yaml

The offline tests take approximately the same length of  time (~15 seconds) to complete.

2021-11-30 09:54 UTC, emilyhcliu commented
@rmclaren I will add yaml files for MHS soon (today!)

2021-11-30 14:43 UTC, rmclaren requested changes
The BUFR files and the .nc files are rather large, usually we use the a tool called subset_bufr.x from https://github.com/aerorahul/bufr-tools  (subset_bufr.x <input_file> <output_file> <percent of file to keep as integer ex: 10>) to try to get these files down to the 200 KB or so level in order to get the amount of data we store in git down, and also to reduce the amount of time it takes to run unit tests. If you want I can do some of this for you.

Having said that, improving performance is my next big goal so these numbers should improve once I've complete.

2021-11-30 14:43 UTC, rmclaren commented on src/bufr/IodaEncoder/IodaEncoder.cpp
> +//  const static char* DefualtDimName = "dim";
Delete commented out code.

2021-11-30 14:43 UTC, rmclaren commented on src/bufr/BufrParser/Exports/Splits/Split.cpp
>  //
delete created by comment

2021-11-30 14:43 UTC, rmclaren commented on src/bufr/BufrParser/Exports/Splits/Split.cpp
> + * (C) Copyright 2020 NOAA/NWS/NCEP/EMC
2021

2021-11-30 14:43 UTC, rmclaren commented on test/testinput/bufr_ncep_1bamua.yaml
> +# (C) Copyright 2021 UCAR
Should this be copyright NOAA/NWS/NCEP/EMC?

2021-11-30 14:43 UTC, rmclaren commented on test/testinput/bufr_ncep_esamua.yaml
> +# (C) Copyright 2021 UCAR
Should this be copyright NOAA/NWS/NCEP/EMC?

2021-11-30 14:43 UTC, rmclaren commented on src/bufr/DataObject.cpp
> + * (C) Copyright 2020 NOAA/NWS/NCEP/EMC
2021

2021-11-30 15:27 UTC, emilyhcliu commented
> The BUFR files and the .nc files are rather large, usually we use the a tool called subset_bufr.x from https://github.com/aerorahul/bufr-tools (subset_bufr.x <input_file> <output_file> <percent of file to keep as integer ex: 10>) to try to get these files down to the 200 KB or so level in order to get the amount of data we store in git down, and also to reduce the amount of time it takes to run unit tests. If you want I can do some of this for you.
> 
> Having said that, improving performance is my next big goal so these numbers should improve once I've complete.

@rmclaren The test data files added were already thinned.   It looks like that the test data files need to be reduced further.  Thanks for point me the BUFR tool from Rahul.  I will update the test data files.

2021-11-30 16:06 UTC, emilyhcliu commented
> https://github.com/aerorahul/bufr-tools

@rmclaren Could you give me an instruction on how to build this tool?   Thanks!

2021-11-30 16:13 UTC, rmclaren commented
The way I do it:

_cd <directory where you cloned bufr_tools>
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=<path where nceplib-bufr is installed> ..
make_

The script sometimes fails for odd reasons though... so you might be better off using your own scripts.

2021-12-22 17:41 UTC, rmclaren approved these changes

2021-12-22 17:42 UTC, merged

2022-01-06 14:30 UTC, emilyhcliu commented
@rmclaren Thanks for merging my branch into feature/query