SPRINT:  Upgrade many converters of satellite data bufr2ioda.x to align with JEDI Data Conventions
JCSDA-internal/ioda-converters pull request #874
Opened 2022-03-16 18:54 UTC by gthompsnJCSDA

## Description

This PR updates 10 converters for satellite data in prepBUFR format using bufr2ioda.x to match the JEDI Data Conventions. Most of the prior versions of yaml files with "_v2" in their name did not have corresponding ctests especially because the global (GDAS) files of satellite data were too large for the repo.  All of the sample files have been greatly shortened.  The following list of YAML files contain the name of each satellite/platform that was tested.

- [x]  bufr_airs.yaml
- [x]  bufr_amsua.yaml
- [x]  bufr_atms.yaml
- [x]  bufr_avhrr.yaml
- [x]  bufr_cris.yaml
- [x]  bufr_hrs.yaml
- [x]  bufr_iasi.yaml
- [x]  bufr_mhs.yaml
- [x]  bufr_sevcrs.yaml
- [x]  bufr_ssmis.yaml

### Issue(s) addressed

Closes #869 

## Acceptance Criteria (Definition of Done)

Reviews and working validation tests.

## Dependencies

Waiting on the following PRs:
- [ ] waiting on JCSDA/ioda/pull/<655>

## Impact

Should be no impacts provided everything is staged in branch ```feature/sprint-ioda-converters```

2022-03-18 15:19 UTC, rhoneyager approved these changes
Approved, though the branch has a file conflict that should be addressed before merging (gdas.t18z.1bmhs.tm00.nc).

The matching ioda branch has been merged.

2022-03-18 17:25 UTC, gthompsnJCSDA commented
> Approved, though the branch has a file conflict that should be addressed before merging (gdas.t18z.1bmhs.tm00.nc).
> 
> The matching ioda branch has been merged.


A variety of minor issues fixed and I think this will now pass CI-testing.

2022-03-22 19:49 UTC, rhoneyager commented
@gthompsnJCSDA There is a conflicting testoutput file. Can you resolve?

@rmclaren, @emilyhcliu, @BenjaminRuston Please review this PR.

2022-03-22 22:06 UTC, rmclaren requested changes

2022-03-22 22:06 UTC, rmclaren commented on test/CMakeLists.txt
> +    testinput/gdas.t00z.atms.tm00.bufr_d
Bufr files are very large... We like to keep them around 200 k or so. You can try the subset_bufr.x utility that Rahul wrote a while ago in order to shrink these files does https://github.com/aerorahul/bufr-tools 

usage: >> subset_bufr.x **<input_file>** **<output_file>** **<percent_of_file_to_keep>**
example: >> `subset_bufr.x input.bufr_d output.bufr_d 10`    # Keeps 10 percent of the messages in the file.

2022-03-22 22:06 UTC, rmclaren commented on test/CMakeLists.txt
> +    testinput/gdas.t00z.ssmisu.tm00.bufr_d
Same as last comment.

2022-03-22 22:24 UTC, emilyhcliu approved these changes

2022-03-22 22:27 UTC, rmclaren commented on test/CMakeLists.txt
> +    testinput/gdas.t00z.atms.tm00.bufr_d
If subset_bufr.x gives you problems (its problematic for some files), Emily has a different way of doing it which might work better.

2022-03-29 16:10 UTC, rhoneyager requested changes
@gthompsnJCSDA Here are the errors.

2022-03-29 16:10 UTC, rhoneyager commented on test/CMakeLists.txt
> +  ecbuild_add_test( TARGET  test_iodaconv_bufr_amsua2ioda
@gthompsnJCSDA This test is failing with "no such file or directory"

2022-03-29 16:29 UTC, gthompsnJCSDA commented on test/CMakeLists.txt
> +  ecbuild_add_test( TARGET  test_iodaconv_bufr_ssmis2ioda
Thank you Ryan - I just made corrections!

2022-03-29 19:38 UTC, rhoneyager approved these changes

2022-03-29 19:38 UTC, merged