Feature/optional python qc
JCSDA-internal/ioda-converters pull request #881
Opened 2022-03-22 18:52 UTC by haydenlj

## Description

added option to turn on georeality QC checks to python converter similar to those found in the FORTRAN converter
added percent confidence check to python QC checks
### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #871 

## Acceptance Criteria (Definition of Done)

Program runs and produces equivalent output

2022-03-22 22:13 UTC, fabiolrdiniz commented
Hi, @haydenlj. Thanks for adding me here. It looks like there is a conflict with this version and the latest develop (please, remember that #879) has been merged already. The coding norms test is failing with this message:
```
525: checking ./gnssro_bufr2ioda.py
525: ./gnssro_bufr2ioda.py:251:13: E127 continuation line over-indented for visual indent
525: ./gnssro_bufr2ioda.py:252:13: E127 continuation line over-indented for visual indent
525: ./gnssro_bufr2ioda.py:253:13: E127 continuation line over-indented for visual indent
525: ./gnssro_bufr2ioda.py:274:5: E122 continuation line missing indentation or outdented
525: 1       E122 continuation line missing indentation or outdented
525: 3       E127 continuation line over-indented for visual indent
```

2022-03-22 23:26 UTC, haydenlj commented
> Hi, @haydenlj. Thanks for adding me here. It looks like there is a conflict with this version and the latest develop (please, remember that #879) has been merged already. The coding norms test is failing with this message:
> 
> ```
> 525: checking ./gnssro_bufr2ioda.py
> 525: ./gnssro_bufr2ioda.py:251:13: E127 continuation line over-indented for visual indent
> 525: ./gnssro_bufr2ioda.py:252:13: E127 continuation line over-indented for visual indent
> 525: ./gnssro_bufr2ioda.py:253:13: E127 continuation line over-indented for visual indent
> 525: ./gnssro_bufr2ioda.py:274:5: E122 continuation line missing indentation or outdented
> 525: 1       E122 continuation line missing indentation or outdented
> 525: 3       E127 continuation line over-indented for visual indent
> ```

Thanks @fabiolrdiniz, I was having some trouble finding the error message. Shouldn't be too hard to fix, I'll get right on it

2022-03-23 21:35 UTC, haydenlj commented
Is there a way I can look in more detail at these failed checks or run them manually to see why they are failing? I can't seem to find the problem

2022-03-28 15:18 UTC, huishao-r approved these changes
Looks good. Thanks!

2022-03-28 23:39 UTC, BenjaminRuston commented on src/gnssro/gnssro_bufr2ioda.py
> +    global qc
very uncomfortable with setting `qc` to a global

and should only need to do it once so confused why it appears more than once?

2022-03-28 23:41 UTC, BenjaminRuston requested changes

2022-03-28 23:41 UTC, BenjaminRuston commented on src/gnssro/gnssro_bufr2ioda.py
> +    if qc:
yes please just pass `qc` into the function if it needs it

and if you ever use `global` doesn't it come before the variable?

2022-03-29 23:32 UTC, BenjaminRuston approved these changes

2022-04-07 22:22 UTC, merged