Modify unit attribute in BUFR2IODA converter and bug fix for satellite winds
JCSDA-internal/ioda-converters pull request #940
Opened 2022-05-07 04:47 UTC by emilyhcliu

## Description

This PR includes the following changes:
(1) Make unit attribute an optional input in YAML
(2) Do not write unit attribute for unitless variables (e.g. qc flag, instrument identifier, ...etc)
(3) bug fixes for satellite wind and update test output
-  change unit deg to degree (to following convention)
- wrong output test file name on CMakeList 
- wrong output directory in YAML 

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #<[939](https://github.com/JCSDA-internal/ioda-converters/issues/939)>

2022-05-07 04:53 UTC, emilyhcliu commented
IODA validator result for satellite wind output file:
```
Processing data file: /scratch1/NCEPDEV/da/Emily.Liu/JEDI/JEDI-ioda-query-cxx/run_satwind/testoutput/2020110112/bufr_ncep_satwind_avhrr.nc
 Verifying that all required groups exist
 Verifying group MetaData
 Verifying group ObsValue
 Verifying group /
 Verifying dimension names
 Verifying variable information
  Variable MetaData/dataProviderOrigin
  Variable MetaData/windDirectionPercentConfidence
  Variable MetaData/sensorCentralFrequency
  Variable MetaData/satelliteIdentifier
  Variable MetaData/windHeightAssignMethod
  Variable MetaData/windSpeedPercentConfidence
  Variable MetaData/satelliteZenithAngle
  Variable MetaData/qualityFlags
  Variable MetaData/longitude
  Variable MetaData/latitude
  Variable MetaData/windSpeedGeneratingApplication
  Variable MetaData/pressure
  Variable MetaData/dateTime
  Variable MetaData/windDirectionGeneratingApplication
  Variable MetaData/windComputationMethod
  Variable ObsValue/windDirection
  Variable ObsValue/windSpeed
Final results:
  # errors:      0
  # warnings:    0

CTEST_FULL_OUTPUT
```

2022-05-09 15:08 UTC, rmclaren requested changes

2022-05-09 20:24 UTC, rmclaren approved these changes

2022-05-09 20:25 UTC, merged

2022-05-09 20:27 UTC, nicholasesposito reviewed
Changes make sense. Looks good to me

2022-05-09 21:09 UTC, YoulongXia-NOAA commented
Look good to me now. Thank you.